dft_foapi:
    path:     /
    defaults: { _controller: dftFoapiBundle:Default:index, _format: json }
    requirements:
      format: json
dft_foapi_ehlo:
    path:     /ehlo/
    defaults: { _controller: dftFoapiBundle:Default:ehlo, _format: json }
    requirements:
      format: json

# Configure API routes.
dft_foapi_printeractivity:
    path: /printer-activity/
    defaults: { _controller: dftFoapiBundle:PrinterActivity:list, _format: json }
    methods:   [GET]
    requirements:
      format: json
dft_foapi_customers:
    path: /customers/
    defaults: { _controller: dftFoapiBundle:Customer:list, _format: json }
    methods:   [GET]
    requirements:
      format: json
dft_foapi_customer_create:
    path: /customer/
    defaults: { _controller: dftFoapiBundle:Customer:create, _format: json }
    methods:   [POST]
    requirements:
          format: json
dft_foapi_customer_verify_password:
    path: /customer/verify-password/
    defaults: { _controller: dftFoapiBundle:Customer:verifyPassword, _format: json }
    methods:   [POST]
    requirements:
          format: json
dft_foapi_customer_update:
    path: /customer/{customerId}
    defaults: { _controller: dftFoapiBundle:Customer:update, _format: json }
    # Unfortunately Symfony2 does not allow for PUT methods.
    methods:   [POST]
    requirements:
          format: json
dft_foapi_customer_verify:
    path: /customer/verify/{customerId}
    defaults: { _controller: dftFoapiBundle:Customer:verify, _format: json }
    # Unfortunately Symfony2 does not allow for PUT methods.
    methods:   [POST]
    requirements:
          format: json
dft_foapi_customer_unverify:
    path: /customer/unverify/{customerId}
    defaults: { _controller: dftFoapiBundle:Customer:unverify, _format: json }
    # Unfortunately Symfony2 does not allow for PUT methods.
    methods:   [POST]
    requirements:
          format: json
dft_foapi_login:
    path: /login/
    defaults: { _controller: dftFoapiBundle:Login:login, _format: json }
    methods: [POST]
    requirements:
          format: json
dft_foapi_logout:
    path: /logout/
    defaults: { _controller: dftFoapiBundle:Login:logout, _format: json }
    methods: [GET]
    requirements:
          format: json
dft_foapi_menuitemcategories:
    path: /menu-item-categories/
    defaults: { _controller: dftFoapiBundle:MenuItemCategories:list, _format: json }
    methods:    [GET]
    requirements:
          format: json
dft_foapi_menuitem_update:
    path: /menu-item/{menuItemId}
    defaults: { _controller: dftFoapiBundle:MenuItem:update, _format: json }
    # Unfortunately Symfony2 is not PUT friendly, so just use a POST here.
    methods:     [POST]
    requirements:
          format: json
dft_foapi_menuitem_create:
    path: /menu-item/
    defaults: { _controller: dftFoapiBundle:MenuItem:create, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_menuitem_delete:
    path: /menu-item/{menuItemId}
    defaults: { _controller: dftFoapiBundle:MenuItem:delete, _format: json }
    methods:     [DELETE]
    requirements:
          format: json
dft_foapi_menuitems_list:
    path: /menu-items/
    defaults: { _controller: dftFoapiBundle:MenuItem:list, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_orders_list:
    path: /orders/
    defaults: { _controller: dftFoapiBundle:Order:list, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_order_create:
    path: /order/
    defaults: { _controller: dftFoapiBundle:Order:create, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_order_cancel:
    path: /order/{orderId}/cancel/
    defaults: { _controller: dftFoapiBundle:Order:cancel, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_order_update:
    path: /order/{orderId}
    defaults: { _controller: dftFoapiBundle:Order:update, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_order_get_single:
    path: /order/{orderId}
    defaults: { _controller: dftFoapiBundle:Order:get, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_restaurant_settings_get_single:
    path: /restaurant-settings/
    defaults: { _controller: dftFoapiBundle:RestaurantSettings:get, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_restaurant_settings_update:
    path: /restaurant-settings/
    defaults: { _controller: dftFoapiBundle:RestaurantSettings:update, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_get_single:
    path: /user/{userId}
    defaults: { _controller: dftFoapiBundle:User:get, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_user_activate:
    path: /user/activate/{userId}
    defaults: { _controller: dftFoapiBundle:User:activate, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_deactivate:
    path: /user/deactivate/{userId}
    defaults: { _controller: dftFoapiBundle:User:deactivate, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_change_password:
    path: /user/change-password/{userId}
    defaults: { _controller: dftFoapiBundle:User:changePassword, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_change_own_password:
    path: /user/change-password/
    defaults: { _controller: dftFoapiBundle:User:changeOwnPassword, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_change_role:
    path: /user/change-role/{userId}
    defaults: { _controller: dftFoapiBundle:User:changeRole, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_update:
    path: /user/{userId}
    defaults: { _controller: dftFoapiBundle:User:update, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_user_create:
    path: /user/
    defaults: { _controller: dftFoapiBundle:User:create, _format: json }
    # Unfortunately Symfony2 is not PUT friendly, so just use a POST here.
    methods:     [POST]
    requirements:
          format: json
dft_foapi_generate_api_access_token:
    path: /generate-api-access-token/
    defaults: { _controller: dftFoapiBundle:ApiToken:generate, _format: json }
    methods:     [POST]
    requirements:
          format: json
dft_foapi_api_access_tokens_get_single:
    path: /api-access-tokens/
    defaults: { _controller: dftFoapiBundle:ApiToken:get, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_user_list:
    path: /users/
    defaults: { _controller: dftFoapiBundle:User:list, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_printer_user_list:
    path: /users/printer
    defaults: { _controller: dftFoapiBundle:User:listPrinterUsers, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_front_end_settings_get_single:
    path: /front-end-settings/
    defaults: { _controller: dftFoapiBundle:FrontEndSettings:get, _format: json }
    methods:     [GET]
    requirements:
          format: json
dft_foapi_front_end_settings_update:
    path: /front-end-settings/
    defaults: { _controller: dftFoapiBundle:FrontEndSettings:update, _format: json }
    methods:     [POST]
    requirements:
          format: json

# Printer web services.
dft_foapi_printer_callback_service:
    path: /printer-callback-service/
    defaults: { _controller: dftFoapiBundle:Printer:callback }
    methods:     [GET]
dft_foapi_printer_pending_orders_service:
    path: /pending-printer-orders/
    defaults: { _controller: dftFoapiBundle:Printer:pending }
    methods:     [GET]