parameters:
    # Code level services.
    dft_foapi.login.class: dft\FoapiBundle\Services\Login
    dft_foapi.menu_item.class: dft\FoapiBundle\Services\MenuItem
    dft_foapi.customer.class: dft\FoapiBundle\Services\Customer
    dft_foapi.printer_activity.class: dft\FoapiBundle\Services\PrinterActivity

services:
    dft_foapi.login:
        class: %dft_foapi.login.class%
        arguments: [@service_container]
    dft_foapi.menu_item:
        class: %dft_foapi.menu_item.class%
        arguments: [@service_container]
    dft_foapi.customer:
        class: %dft_foapi.customer.class%
        arguments: [@service_container]
    dft_foapi.printer_activity:
        class: %dft_foapi.printer_activity.class%
        arguments: [@service_container]
    # Event listener for onKernelController, used for verifying if a user is authenticated.
    dft_foapi.request_listener:
        class: dft\FoapiBundle\EventListener\AuthenticationListener
        arguments: [@service_container, @router]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }