parameters:
    # Code level services.
    dft_foapi.login.class: dft\FoapiBundle\Services\Login

services:
    dft_foapi.login:
        class: %dft_foapi.login.class%
        arguments: [@service_container]