parameters:
    # Code level services.
    dft_foapi.login.class: dft\FoapiBundle\Services\Login
    dft_foapi.menu_item.class: dft\FoapiBundle\Services\MenuItem
    dft_foapi.customer.class: dft\FoapiBundle\Services\Customer
    dft_foapi.printer_activity.class: dft\FoapiBundle\Services\PrinterActivity
    dft_foapi.order.class: dft\FoapiBundle\Services\Order
    dft_foapi.user.class: dft\FoapiBundle\Services\User
    dft_foapi.menu_item_categories.class: dft\FoapiBundle\Services\MenuItemCategories
    dft_foapi.restaurant_settings.class: dft\FoapiBundle\Services\RestaurantSettings
    dft_foapi.barclays_payment_settings.class: dft\FoapiBundle\Services\BarclaysPaymentSettings
    dft_foapi.sms_gateway.class: dft\FoapiBundle\Services\SMSGateway
    dft_foapi.sms_notification_settings.class: dft\FoapiBundle\Services\SMSNotificationSettings
    dft_foapi.front_end_settings.class: dft\FoapiBundle\Services\FrontEndSettings
    dft_foapi.front_end_discounts.class: dft\FoapiBundle\Services\FrontEndDiscounts
    dft_foapi.printer.class: dft\FoapiBundle\Services\Printer
    dft_foapi.api_token.class: dft\FoapiBundle\Services\ApiToken
    dft_foapi.image.class: dft\FoapiBundle\Services\Image
    dft_foapi.order_confirmation_email.class: dft\FoapiBundle\Services\OrderConfirmationEmail
    dft_foapi.service_coverage.class: dft\FoapiBundle\Services\ServiceCoverage
    dft_foapi.email_templates.class: dft\FoapiBundle\Services\EmailTemplates
    dft_foapi.statistics.class: dft\FoapiBundle\Services\Statistics

services:
    dft_foapi.login:
        class: %dft_foapi.login.class%
        arguments: [@service_container]
    dft_foapi.sms_gateway:
        class: %dft_foapi.sms_gateway.class%
        arguments: [@service_container]
    dft_foapi.user:
        class: %dft_foapi.user.class%
        arguments: [@service_container]
    dft_foapi.order:
        class: %dft_foapi.order.class%
        arguments: [@service_container]
    dft_foapi.menu_item:
        class: %dft_foapi.menu_item.class%
        arguments: [@service_container]
    dft_foapi.menu_item_categories:
        class: %dft_foapi.menu_item_categories.class%
        arguments: [@service_container]
    dft_foapi.image:
        class: %dft_foapi.image.class%
        arguments: [@service_container]
    dft_foapi.customer:
        class: %dft_foapi.customer.class%
        arguments: [@service_container]
    dft_foapi.printer:
        class: %dft_foapi.printer.class%
        arguments: [@service_container]
    dft_foapi.printer_activity:
        class: %dft_foapi.printer_activity.class%
        arguments: [@service_container]
    dft_foapi.restaurant_settings:
        class: %dft_foapi.restaurant_settings.class%
        arguments: [@service_container]
    dft_foapi.sms_notification_settings:
        class: %dft_foapi.sms_notification_settings.class%
        arguments: [@service_container]
    dft_foapi.barclays_payment_settings:
        class: %dft_foapi.barclays_payment_settings.class%
        arguments: [@service_container]
    dft_foapi.front_end_settings:
        class: %dft_foapi.front_end_settings.class%
        arguments: [@service_container]
    dft_foapi.email_templates:
        class: %dft_foapi.email_templates.class%
        arguments: [@service_container]
    dft_foapi.front_end_discounts:
        class: %dft_foapi.front_end_discounts.class%
        arguments: [@service_container]
    dft_foapi.api_token:
        class: %dft_foapi.api_token.class%
        arguments: [@service_container]
    dft_foapi.statistics:
        class: %dft_foapi.statistics.class%
        arguments: [@service_container]
    dft_foapi.order_confirmation_email:
        class: %dft_foapi.order_confirmation_email.class%
        arguments: [@service_container]
    dft_foapi.service_coverage:
        class: %dft_foapi.service_coverage.class%
        arguments: [@service_container]
    # Event listener for onKernelRequest, used for verifying if a user is authenticated.
    dft_foapi.request_listener:
        class: dft\FoapiBundle\EventListener\AuthenticationListener
        arguments: [@service_container, @router]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
    # Event listener for onKernelException, used for generating JSON formatted 404 responses.
    dft_foapi.exception_listener:
        class: dft\FoapiBundle\EventListener\KernelExceptionListener
        arguments: [@templating, @kernel]
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
